### ISSUE TITLE
text diff rawData result shouldnt be in uni diff/patch format

### ISSUE THREAD

**Issue by tu1ly** [apiaryio/gavel.js#15]
may be as an option, not as one and only output. there is no node/js lib/module (afaik) which can work with this kind of data as an input. we don't want to patch data, we want to visualize it ...

**Comment by honzajavorek** [comment]
@tu1ly @Almad Is this still relevant?

**Comment by Almad** [comment]
@honzajavorek I am not aware of us changing it, but talk to tully.

**Comment by artem-zakharchenko** [comment]
According to the [re-designed API](#221 ) HTTP components (fields) in the validation result no longer contain the `rawData` key. It has been previously used:

* `gavel2html`  uses to handle Amanda result (errors). Outputs error messages coming from `rawData[n].message`  and composes JSON pointers from `rawData[n].property`. Other properties are *ignored*.

Therefore a decision has been made to remove this rather internal field and expose a proper validation error structure. That structure will now contain a `location` property that describes extra information about the error.

I believe we can close this ticket, as the `rawData` field is no longer present.
