### ISSUE TITLE
Order of validation matters

### ISSUE THREAD

**Issue by artem-zakharchenko** [apiaryio/gavel.js#169]
Upon investigating the [failing Dredd CI](https://travis-ci.org/apiaryio/dredd/jobs/534710787) I have found an interesting behavior: the order of validation matters, as it gets asserted in Dredd. Moreover, the output of Dredd also relies on the order of validation (see Current behavior for more details).

By the "order of validation" I mean the order in which dedicated validators are executed:

https://github.com/apiaryio/gavel.js/blob/c03a0f917f5bb9ba37ea63e2171e06361c08e349/lib/next/validateMessage.js#L7-L28

> In the code above you can see that `statusCode` is being validated first, then `headers`, then `body`. That is the order.

This may be clear from the Dredd's perspective to have a proper logging, but the order of validation must not matter on Gavel's side. The validation results is an Object, key order of which cannot be important by Object's design. I find it unexpected to demand a specific validation order from Gavel.

## Current behavior

Currently the order `statusCode > headers > body` is being unexpected in Dredd tests:

https://github.com/apiaryio/dredd/blob/306528427176c6b6d3f7e2eed8a27afdd5b063b7/test/integration/response-test.js#L264-L266

> The test above asserts that the `body` is validated before `statusCode`, which produces the right order of logging output.

## Expected behavior

1. Figure out why the order has been important in the first place. Is this for logging only? Then wen can adjust the logging of Dredd, outputting Gavel's results in the order necessary.
1. Make both implementations treat validation result without relying on the order of validation occurred. I want to strive toward Gavel's design treating validators as independent functions. In the future it would be great to allow executing validators of specific kind (i.e. `validateBody(real, expected)`) as a part of public API.

> Changing the order of execution on Gavel's side to validate `statusCode` last fixes the Dredd CI, but I don't believe that is the proper fix here.

**Comment by artem-zakharchenko** [comment]
I've address this issue on Dredd's level https://github.com/apiaryio/dredd/issues/1371. This should be a proper place to specify the order of validators, not Gavel.

**Comment by honzajavorek** [comment]
I think it is correct to address this on Dredd tests' side - we shouldn't expect certain order of the properties in the validation result object. And if, then we should expect it in an order natural to human thinking about HTTP responses, i.e. 1) status code, 2) headers, 3) body.

I suggest to close this issue as apart from fixing Dredd's tests, it's not actionable on Gavel side. What do you think?

**Comment by artem-zakharchenko** [comment]
@honzajavorek I kept the same image in mind: status code, headers, body.

This issue will be closed once the respective Dredd's issue is resolved. Thanks!
