### ISSUE TITLE
statusMessage validation

### ISSUE THREAD

**Issue by artem-zakharchenko** [apiaryio/gavel.js#193]
It seems that the `statusMessage` field of an HTTP message has been lost during the refactoring of Gavel.

Should we still support `statusMessage`, as it seems to be deprecated in HTTP2?

**Comment by honzajavorek** [comment]
What exactly is status message? Is that the reason phrase, like `OK` or `Not Found`? If yes, I don't see much benefit in validating it. Even in HTTP v1.x it is usually an enumeration within a programming framework and not something anyone really sets manually or has much way to influence. I'd focus on the status code only.

**Comment by artem-zakharchenko** [comment]
Yes, `statusMessage` is a verbose representation of a response's status. I agree on your points. We do cover the validation of `statusCode`, but we should write a changelog notice that `statusMessage` is no longer validated by the library.

**Comment by honzajavorek** [comment]
Agreed.

**Comment by artem-zakharchenko** [comment]
Added breaking change mentioning the removal of `statusMessage` validation: https://github.com/apiaryio/gavel.js/releases/tag/v6.0.0
