### ISSUE TITLE
Transition from "isValid" to "valid" is not anywhere in changelog

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/gavel.js#249]
The property `isValid` has been renamed to `valid`, but there is no mention of it in the changelog. This issue can be closed once the changelog is appropriately edited.

**Comment by artem-zakharchenko** [comment]
Version [`6.0.0`](https://github.com/apiaryio/gavel.js/releases/tag/v6.0.0) includes the following:

```
removes "isValid" from public API (969ab5a)
```

It must also mention that it has been replaced by `valid`. Will update.

**Comment by artem-zakharchenko** [comment]
Changed to:

```
Uses "valid" instead of "isValid" on the top-level of a validation result to indicate the validity of the given message (969ab5a)
```

**Comment by honzajavorek** [comment]
That's better, thanks!
