### ISSUE TITLE
Value mismatch in a body's property is not considered invalid

### ISSUE THREAD

**Issue by artem-zakharchenko** [apiaryio/gavel.js#267]
## Scenario

```js
gavel.validate(
    {
      body: JSON.stringify({
        "login": "admin"
      })
    },
    {
      body: JSON.stringify({
        "login": "octocat"
      })
    }
)
```

This call produces the next validation result:

```js
{
  "valid": true,
  "fields": {
    "body": {
      "valid": true,
      "kind": "json",
      "values": {
        "actual": "{\"login\":\"octocat\"}",
        "expected": "{\"login\":\"admin\"}"
      },
      "errors": []
    }
  }
}
```

## Expected

I think if an actual body's property value doesn't match the expected value of the same property, this should produce a validation error stating that the value of the property doesn't match.

**Comment by artem-zakharchenko** [comment]
This is the reason why such HTTP messages scenario in the core app doesn't highlight the `login` property as invalid (with red).

**Comment by honzajavorek** [comment]
IMHO this might be an expected behavior. By default, if not provided with a schema, Gavel infers its own schema, which only checks presence of properties, not their values: http://dredd.org/en/latest/how-it-works.html#gavels-expectations

**Comment by artem-zakharchenko** [comment]
So it's expected if I write the following API Blueprint:

```apib
+ Response 200 (application/json)
  + Body
      {
        "login": "admin"
      }
```

And the actual response is:

```json
{
  "login": "not_admin"
}
```

The diff will not highlight that the `login` property mismatches.

**Comment by honzajavorek** [comment]
The diff should show the property, but with with neutral color. They shouldn't be either red or green, or missing from the diff.

If Dredd and Gavel were strict, they wouldn't be useful most of the time. There's plenty of dynamic content in the APIs. They based on automatic expectations instead, which are "best guess" on what's okay to be ignored and what's important to check (hence checking values of content negotiation headers, but not the others). This is of course sorcery and magic, but not so much if it's properly documented, and it's one of the reasons why people like to use Dredd.

Apart from "best guess sensible defaults", both Dredd and Gavel should provide ways for users to make the comparison stricter, so if they want, they can do it. That's in this case possible specifying your own JSON Schema and not relying on inferred expectations:

```apib

+ Response 200 (application/json)
    
    + Body

        {
          "login": "admin"
        }

    + Schema

        {
          "type": "object",
          "properties": {
            "login": {
              "type": "string",
              "enum": ["admin"]
            }
          },
          "required": ["login"]
        }
```

...or using [MSON](https://github.com/apiaryio/mson) in the `+ Attributes` section, which generates the schema for you.

**Comment by artem-zakharchenko** [comment]
> The diff should show the property, but with with neutral color. They shouldn't be either red or green, or missing from the diff.

I confirm this is how diff'ing works on production at the moment. Thank you for explanation on this behavior :) Closing this.
