### ISSUE TITLE
validation always pass if body is empty an object ( {} ) or an empty array ( [] ).

### ISSUE THREAD

**Issue by tu1ly** [apiaryio/gavel.js#41]
body: '{}'

bodySchema: {
    '$schema': 'http://json-schema.org/draft-03/schema',
    id: '#',
    required: true,
    additionalProperties: true,
    type: 'object',
    properties: {
      mesage: { id: 'mesage', required: true }
    }
  }

{ results: [],
  realType: 'application/json',
  expectedType: 'application/schema+json',
  validator: 'JsonSchema',
  rawData: { length: 0 } }

**Comment by honzajavorek** [comment]
I believe this should be fixed by https://github.com/apiaryio/gavel.js/pull/49. If that's not true, please re-open.
