### ISSUE TITLE
JSON schema to result comparison not catching changes to key name.

### ISSUE THREAD

**Issue by cdel46** [apiaryio/gavel.js#58]
I'm new to Dredd so I may be doing it wrong. I was having issues getting an invalid key name to fail in dredd until I changed line 231 in gavel/lib/validators/json-schema.js: (173 in json-schema.coffee)

Old:     result = tv4.validateMultiple(this.data, this.schema);
New:    result = tv4.validateMultiple(this.data, this.schema, true, true);

Schema Expected:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
    "enable": {
        "type": "boolean",
        "description": "True if login button should be enabled, false is disabled."
    },
    "message": {
        "type": "string",
        "description": "Alert message to be rendered in alert field."
    }
}
```

Passing Result from server (deliberately intended to fail but doesn't without patch)

```json
{
  "enXXXXable": true,
  "message": "Some Message Here."
}
```

Apib file excerpt:
```apib
### GetAlerts [POST /Mobile/GetAlerts]

+ Request (application/json)
    + Attributes
        + appver: 1.0 (string) - Current app version
        + platform: Google Android (required,string) - Operating Sysetm
        + platformversion: 4.1.2 (required,string) - Operating Sysetm version

+ Response 200 (application/json)
    + Attributes
        + enable: true (boolean) - True if login button should be enabled, false is disabled.
        + message: Some Message Here (string)
```

----------------
Node: 4.4.3
Dredd: 1.1.0-pre.0
Gavel: 0.5.2

**Comment by honzajavorek** [comment]
Thanks for reporting this! Would you please try whether it works correctly with `v1.0.x` version of Dredd?

**Comment by honzajavorek** [comment]
@cdel46 I looked closer at your issue :microscope: and it seems there is a problem with your JSON Schema in the first place. JSON Schema allows additional properties of any name by default. Moreover, `enable` isn't marked as `required` in your schema. So Gavel correctly treats `enXXXXable` as an additional property and at the same time it doesn't complain about `enable` missing.

To do what you want, you either need to mark `enable` as required or use `additionalProperties` - see http://spacetelescope.github.io/understanding-json-schema/reference/object.html. I hope this helps.

Please re-open this issue in case you still have problems to achieve what you want! :balloon:
