### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/gavel.js#65]
It contains links to non-existing docs etc. It should undergo some facelift. Issues reported by @XVincentX.

**Comment by XVincentX** [comment]
A good starting point would be to move [relishapp](https://www.relishapp.com/apiary/gavel/docs) content into the readme.

**Comment by XVincentX** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Lk3Ub4Ir&#x2F;148-try-to-document-the-things-while-using-gavel-and-gavel2html"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Try to document the things while using gavel and gavel2html</a>

**Comment by honzajavorek** [comment]
@XVincentX I made some changes in how the docs are handled, but due to the nature of its contents, most of the valuable information will be on Relish now.

At the same time, I'd like to replace Relish with something else in the future - https://github.com/apiaryio/gavel-spec/issues/21. Once #74 gets merged, I'd like to hear your feedback on whether the docs improved at least a bit and are more understandable.
